package entity.enums;

public enum GradeEnum {
   ASSOCIATE,
    DISCONTINUOUS_BACHELOR,
    CONTINUOUS_BACHELOR,
    DISCONTINUOUS_MASTER,
    CONTINUOUS_MASTER,
    DISCONTINUOUS_PROFESSIONAL_DOCTOR,
    CONTINUOUS_DOCTOR,
    PROFESSIONAL_DOCTOR

}
