package entity.enums;

public enum UniversityEnum {
    SHABANEH_UNIVERSITY,
    GHEYREH_ENTEFAEE_UNIVERSITY,
    PARDIS_UNIVERSITY,
    ZARFIAT_MAZAD_UNIVERSITY,
    PAYAME_NOUR_UNIVERSITY,
    ELMI_KARBORDI_UNIVERSITY,
    AZAD_UNIVERSITY,
    DOLATI_ROZANEH_UNIVERSITY,
    DOLATI_SHABANEH_UNIVERSITY
}
